### ISSUE TITLE
Use MicroProfile Health new API in MP 3.3

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/guide-microprofile-health#108]
@ApplicationScoped
public class SystemReadinessCheck implements HealthCheck {
  @Override
  public HealthCheckResponse call() {
    if (!System.getProperty("wlp.server.name").equals("defaultServer")) {
      _return HealthCheckResponse.named(SystemResource.class.getSimpleName() + "Readiness")
                                .withData("default server", "not available").down()
                                .build();_
    }
    return HealthCheckResponse.named(SystemResource.class.getSimpleName() + "Readiness")
                              .withData("default server", "available").up().build();
  }
}

=> 
HealthCheckResponse has changed to be a concrete class the line in italic can be simplied.

**Comment by gkwan-ibm** [comment]
- ready for dev content review

**Comment by gkwan-ibm** [comment]
- [ ] guide-getting-started
- [ ] guide-kubernetes-microprofile-health
- [ ] guide-microprofile-health

**Comment by DannyS03** [comment]
Hi @Emily-Jiang, would you mind reviewing the code change.
- https://github.com/OpenLiberty/guide-microprofile-health/pull/111
- https://github.com/OpenLiberty/guide-microprofile-health/tree/mphealth-2.2

**Comment by ankitagrawa** [comment]
- Ran into an issue while updating it to the next version. Waiting for Emily's reply.
