### ISSUE TITLE
No reference of HealthCheckResponse.builder in file

### ISSUE THREAD

**Issue by NimG98** [OpenLiberty/guide-microprofile-health#114]
In the [Adding health checks to the system service](https://openliberty.io/guides/microprofile-health.html#adding-health-checks-to-the-system-service) section, it has the following:

![image](https://user-images.githubusercontent.com/46586499/81098700-be4c3680-8ed7-11ea-995a-4c9020d51c4e.png)

However, the hotspot `HealthCheckResponse.builder()` points to nothing and the `HealthCheckResponse.builder()` function is not used at all in the `SystemReadinessCheck.java`
 file.

**Comment by gkwan-ibm** [comment]
https://github.com/OpenLiberty/guide-microprofile-health/pull/117

**Comment by DannyS03** [comment]
Merged and verified.
