### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-microprofile-health#40]
- Can take another pass with a fresh critical pair of eyes to review and edit the guide and the provided implementation to tidy things up and make things clearer

- Data returned by the HealthCheckResponses can be improved to have better names and descriptions especially if we will show a sample response of the `/health` endpoint

- A better exercise for users to experiment with the provided automated tests

**Comment by JunyiSun** [comment]
One more suggestion, should those extra config stuff in the health code been cleaned up? I remember those files were asked to be removed before INDEX. But it’s okay at this moment, not critical and we can think about it later

**Comment by evelinec** [comment]
Assign to @JunyiSun to work on the suggested areas.

**Comment by evelinec** [comment]
Perhaps this point hasn't been addressed? Don't see it anywhere.

- A better exercise for users to experiment with the provided automated tests

**Comment by JunyiSun** [comment]
@evelinec Isn't the automated test something that we will work in the future under guides-common?

**Comment by evelinec** [comment]
@JunyiSun No, that's not related to this. We had discussed this during scrum, pls update with your latest finding. Thanks.

**Comment by JunyiSun** [comment]
fixed by #44 #42 #45

**Comment by gkwan-ibm** [comment]
Close this issue.
Assumed issues were fixed. The guide was updated for dev mode and mpHealth-2.2
