### ISSUE TITLE
Hard to understand paragraph

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-microprofile-health#58]
_This time, you are checking whether or not the service is in maintenance or if it’s down. For simplicity, a custom io_openliberty_guides_inventory_inMaintenance MicroProfile Config property defined in the resources/CustomConfigSource.json file is used to indicate whether the service is in maintenance or not. This file has already been created for you. To check if the service is down, simply make a HTTP GET request to the system service and check the status returned by the response. You make a GET request to the system service rather than the inventory service because the inventory service depends on the system service. In other words, the inventory service wouldn’t work if the system service is down. If the status is not 200, then the service is not running. Based on these two factors, the isHealthy() method returns whether or not the inventory service is healthy._

The above is dense.  And, it jumps from one aspect to another without providing adequate context for users to follow.  We should rewrite to make it simpler and provide clearer context as to what is done for what and why.

**Comment by gkwan-ibm** [comment]
close
- the paragraph was rewritten
