### ISSUE TITLE
Multipane Issue

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/guide-microprofile-health#69]
### Checklist for Post-Review
**Through the browser:**
- [x] Read through guide, making sure that the flow of the guide is good
- [x] Click all links to make sure they lead to the correct place
- [x] Make sure hotspots, code_commands and files are correct
- [x] Run Acrolinx
----------
### Issues
- [ ] Maybe you can address this while converting: https://github.com/OpenLiberty/guide-microprofile-health/issues/58
- [x] Missing "in Open Liberty" after `Nice work, you did it!` 
- [x]  I don't think the localhost links needs to be backticked because it's clickable
- [x] `src/main/liberty/config/server.xml` should highlight the entire `server.xml` file 
- [x] `resources/CustomConfigSource.json` should be a hotspot of the entire file (happens twice)
- [x] `src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java` shouldn't hotspot the import statements
- [x] `src/test/java/it/io/openliberty/guides/system/SystemEndpointTest.java` shouldn't hotspot the import statements

**Comment by andrewdes** [comment]
2nd Round Review:
- [ ] guide author
- [x] branch is up to date with master
- [ ] mvn insturctions

 ```
cd finish
mvn install liberty:start-server
```
- [ ] if there is a clean comment, let consider or discuss it
- [ ] make sure liberty:stop-server
- [ ] update the version of cxf-rt-rs-client and cxf-rt-rs-extension-providers to 3.2.6
