### ISSUE TITLE
multipane issues

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-health#72]
- [x] URLs do not open in new tab
- [x] should format the server.xml
`  <httpEndpoint host="*" httpPort="${default.http.port}" httpsPort="${default.https.port}" id="defaultHttpEndpoint"/>`
- [x] "Create the SystemHealth class", "Create the InventoryHealth class.", "Create the HealthTest class."  highlighted the code

**Comment by justineechen** [comment]
https://github.com/OpenLiberty/guide-microprofile-health/commit/ab1f10960180682fe87a8e79eb28e1220603fedf
