### ISSUE TITLE
Syntax Errror seen with last paragraph "Building and running the application"

### ISSUE THREAD

**Issue by susanodom** [OpenLiberty/guide-microprofile-health#79]
With the MP Health docs guide, I got “**SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data**” (in JSON tab) with last paragraph of "Building and running the application", see below:

“…Point to the http://localhost:9080/inventory/systems URL to verify that the inventory service is indeed in maintenance. Set the io_openliberty_guides_inventory_inMaintenance property back to false once you are done.”

With the "Raw Data" tab, I did see “ERROR: Service is currently in maintenance".

The problem is only seen if the property value is set to true.  If I changed the property value back to false, everything is fine.

**Comment by yeekangc** [comment]
Susan was working with Firefox.

**Comment by justineechen** [comment]
Hi @susanodom, thank you for letting us know about this issue. 
It looks like the application is expecting a JSON but the error message is in plain text. I will work on this fix now.
